//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCode.WorkHoursTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkHoursTrackTemplate.xlsx")]
        public string WorkHoursTemplateFileName {
            get {
                return ((string)(this["WorkHoursTemplateFileName"]));
            }
            set {
                this["WorkHoursTemplateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkHoursDirectory")]
        public string WorkHoursDirectoryRegistryName {
            get {
                return ((string)(this["WorkHoursDirectoryRegistryName"]));
            }
            set {
                this["WorkHoursDirectoryRegistryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TimerIntervalInMinutes")]
        public string TimerIntervalInMinutesRegistryName {
            get {
                return ((string)(this["TimerIntervalInMinutesRegistryName"]));
            }
            set {
                this["TimerIntervalInMinutesRegistryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VisibilityIntervalInSeconds")]
        public string VisibilityIntervalInSecondsRegistryName {
            get {
                return ((string)(this["VisibilityIntervalInSecondsRegistryName"]));
            }
            set {
                this["VisibilityIntervalInSecondsRegistryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter Working Hours directory ...")]
        public string WorkHoursDirectoryDefaultValue {
            get {
                return ((string)(this["WorkHoursDirectoryDefaultValue"]));
            }
            set {
                this["WorkHoursDirectoryDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public uint TimerIntervalInMinutesDefaultValue {
            get {
                return ((uint)(this["TimerIntervalInMinutesDefaultValue"]));
            }
            set {
                this["TimerIntervalInMinutesDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint VisibilityIntervalInSecondsDefaultValue {
            get {
                return ((uint)(this["VisibilityIntervalInSecondsDefaultValue"]));
            }
            set {
                this["VisibilityIntervalInSecondsDefaultValue"] = value;
            }
        }
    }
}
